# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Player.create!(last_name: "Arroyo", first_name: "Bronson", photo: "arroyo.jpg", age: 27, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Embree", first_name: "Alan", photo: "embree.jpg", age: 34, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Foulke", first_name: "Keith", photo: "foulke.jpg", age: 31, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Leskanic", first_name: "Curtis", photo: "leskanic.jpg", age: 35, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Lowe", first_name: "Derek", photo: "lowe.jpg", age: 30, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Martínez", first_name: "Pedro", photo: "martinez.jpg", age: 32, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Myers", first_name: "Mike", photo: "myers.jpg", age: 34, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Schilling", first_name: "Curt", photo: "schilling.jpg", age: 37, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Timlin", first_name: "Mike", photo: "timlin.jpg", age: 37, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Wakefield", first_name: "Tim", photo: "wakefield.jpg", age: 37, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Mirabelli", first_name: "Doug", photo: "mirabelli.jpg", age: 33, position: 2, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Varitek", first_name: "Jason", photo: "varitek.jpg", age: 31, position: 2, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Bellhorn", first_name: "Mark", photo: "bellhorn.jpg", age: 29, position: 4, bats: 2, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Cabrera", first_name: "Orlando", photo: "cabrera.jpg", age: 29, position: 5, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Mientkiewicz", first_name: "Doug", photo: "mientkiewicz.jpg", age: 29, position: 3, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Millar", first_name: "Kevin", photo: "millar.jpg", age: 32, position: 3, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Mueller", first_name: "Bill", photo: "mueller.jpg", age: 29, position: 6, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Ortiz", first_name: "David", photo: "ortiz.jpg", age: 28, position: 3, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Reese", first_name: "Pokey", photo: "reese.jpg", age: 30, position: 4, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Youkilis", first_name: "Kevin", photo: "youkilis.jpg", age: 24, position: 6, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Damon", first_name: "Johnny", photo: "damon.jpg", age: 30, position: 8, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Kapler", first_name: "Gabe", photo: "kapler.jpg", age: 28, position: 7, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Nixon", first_name: "Trot", photo: "nixon.jpg", age: 29, position: 9, bats: 1, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Ramirez", first_name: "Manny", photo: "ramirez.jpg", age: 31, position: 7, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Roberts", first_name: "Dave", photo: "roberts.jpg", age: 31, position: 8, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Adams", first_name: "Terry", photo: "adams.jpg", age: 31, position: 1, bats: 0, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Alvarez", first_name: "Abe", photo: "alvarez.jpg", age: 11, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Anderson", first_name: "Jimmy", photo: "anderson.jpg", age: 28, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Astacio", first_name: "Pedro", photo: "astacio.jpg", age: 35, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Brown", first_name: "Jamie", photo: "brown.jpg", age: 27, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Burks", first_name: "Ellis", photo: "burks.jpg", age: 39, position: 8, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Castillo", first_name: "Frank", photo: "castillo.jpg", age: 35, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Crespo", first_name: "César", photo: "crespo.jpg", age: 25, position: 4, bats: 2, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Daubach", first_name: "Brian", photo: "daubach.jpg", age: 32, position: 3, bats: 1, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "DiNardo", first_name: "Lenny", photo: "dinardo.jpg", age: 24, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Dominique", first_name: "Andy", photo: "dominique.jpg", age: 28, position: 3, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Garciaparra", first_name: "Nomar", photo: "garciaparra.jpg", age: 30, position: 5, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Gutierrez", first_name: "Ricky", photo: "gutierrez.jpg", age: 34, position: 5, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Hyzdu", first_name: "Adam", photo: "hyzdu.jpg", age: 32, position: 8, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Jones", first_name: "Bobby", photo: "jones.jpg", age: 32, position: 1, bats: 0, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Malaska", first_name: "Mark", photo: "malaska.jpg", age: 26, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Martínez", first_name: "Anastacio", photo: "anastacio.jpg", age: 25, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Martínez", first_name: "Sandy", photo: "sandy.jpg", age: 33, position: 2, bats: 1, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "McCarty", first_name: "Dave", photo: "mccarty.jpg", age: 34, position: 3, bats: 0, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Ramiro", first_name: "Mendoza", photo: "mendoza.jpg", age: 32, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Nelson", first_name: "Joe", photo: "nelson.jpg", age: 29, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Seibel", first_name: "Phil", photo: "seibel.jpg", age: 25, position: 1, bats: 1, throws: 1, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Snyder", first_name: "Earl", photo: "snyder.jpg", age: 28, position: 6, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
Player.create!(last_name: "Williamson", first_name: "Scott", photo: "williamson.jpg", age: 28, position: 1, bats: 0, throws: 0, current_year_salary: nil, free_agent_year: nil)
